"""initial tables

Revision ID: a74fd0848ea6
Revises:
Create Date: 2026-04-17 04:47:30.252374

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a74fd0848ea6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cedentes",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("document", sa.String(length=18), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document"),
    )
    op.create_table(
        "currencies",
        sa.Column("code", sa.String(length=3), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "receivable_types",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("spread_rate", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "exchange_rates",
        sa.Column("from_currency_id", sa.Uuid(), nullable=False),
        sa.Column("to_currency_id", sa.Uuid(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_currency_id"],
            ["currencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_currency_id"],
            ["currencies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exchange_rates_effective_date"),
        "exchange_rates",
        ["effective_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exchange_rates_from_currency_id"),
        "exchange_rates",
        ["from_currency_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exchange_rates_to_currency_id"),
        "exchange_rates",
        ["to_currency_id"],
        unique=False,
    )
    op.create_table(
        "transactions",
        sa.Column("cedente_id", sa.Uuid(), nullable=False),
        sa.Column("receivable_type_id", sa.Uuid(), nullable=False),
        sa.Column("face_value", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("present_value", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("currency_id", sa.Uuid(), nullable=False),
        sa.Column("payment_currency_id", sa.Uuid(), nullable=False),
        sa.Column("exchange_rate_used", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("term_months", sa.Integer(), nullable=False),
        sa.Column("base_rate", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("spread_applied", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cedente_id"],
            ["cedentes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_currency_id"],
            ["currencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["receivable_type_id"],
            ["receivable_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_cedente_id"), "transactions", ["cedente_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_created_at"), "transactions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_currency_id"), "transactions", ["currency_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_payment_currency_id"),
        "transactions",
        ["payment_currency_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_payment_currency_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_currency_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_created_at"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_cedente_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_exchange_rates_to_currency_id"), table_name="exchange_rates")
    op.drop_index(op.f("ix_exchange_rates_from_currency_id"), table_name="exchange_rates")
    op.drop_index(op.f("ix_exchange_rates_effective_date"), table_name="exchange_rates")
    op.drop_table("exchange_rates")
    op.drop_table("receivable_types")
    op.drop_table("currencies")
    op.drop_table("cedentes")
    # ### end Alembic commands ###
